import { NextResponse } from "next/server";
import { auth } from "@/lib/auth/config";
import { prisma } from "@/lib/db/prisma";
import { sendEmail } from "@/lib/email/smtp";
import { z } from "zod";
const schema=z.object({sourceProgram:z.string().min(2),destinationProgram:z.string().min(2),bonusPercent:z.number().int().min(1).max(300),validFrom:z.string().optional(),validUntil:z.string(),officialUrl:z.string().url()});
async function admin(){const session=await auth();return session?.user?.role==="ADMIN"?session:null;}
export async function GET(){if(!await admin())return NextResponse.json({error:"Acesso negado."},{status:403});return NextResponse.json({promos:await prisma.mileageTransferPromo.findMany({orderBy:{createdAt:"desc"},take:100})});}
export async function POST(request:Request){const session=await admin();if(!session?.user?.id)return NextResponse.json({error:"Acesso negado."},{status:403});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Dados inválidos.",details:parsed.error.flatten()},{status:400});const promo=await prisma.mileageTransferPromo.create({data:{...parsed.data,validFrom:parsed.data.validFrom?new Date(parsed.data.validFrom):new Date(),validUntil:new Date(parsed.data.validUntil),createdById:session.user.id}});const subscribers=await prisma.mileagePromoSubscription.findMany({where:{active:true},include:{user:true}});for(const sub of subscribers){const result=await sendEmail({to:sub.user.email,subject:`Transferência bonificada: até ${promo.bonusPercent}%`,text:`${promo.sourceProgram} → ${promo.destinationProgram}\nBônus: ${promo.bonusPercent}%\nVálida até ${promo.validUntil.toLocaleDateString("pt-BR")}\n${promo.officialUrl}`});await prisma.notificationLog.create({data:{userId:sub.userId,type:"MILEAGE_PROMO",channel:"email",recipient:sub.user.email,status:result.ok?"sent":"error",provider:promo.destinationProgram,messageId:result.messageId,error:result.error}});}return NextResponse.json({promo},{status:201});}
